env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - prettier
settings:
  react:
    version: detect
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jsx-a11y
  - import
rules:
  {
    camelcase: [0, { 'properties': 'always' }],
    eqeqeq: [2, always],
    import/no-extraneous-dependencies: [1, { devDependencies: ['**.config.js'] }],
    react/function-component-definition: [2, { 'namedComponents': 'arrow-function' }],
    no-restricted-exports: [off],
    react/jsx-props-no-spreading: 0,
    no-console: 1,
    linebreak-style: ['off', 'windows'],
    react/react-in-jsx-scope: [off],
    import/extensions:
      [0, 'ignorePackages', { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' }],
    import/no-unresolved: [0, { 'caseSensitive': false }],
    jsx-a11y/anchor-is-valid: 'off',
    jsx-a11y/control-has-associated-label: 'off',
    no-plusplus: 'off',
    react/require-default-props: 'off',
    import/prefer-default-export: 'off',
  }
