name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "develop"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
      - name: Install and Build
        run: |
          yarn install
          yarn build-storybook
      - name: Deploy
        uses: YisoTsao/UI-lib-to-github-pages@v1.0.0
        with:
          branch: gh-pages
          folder: storybook-static 

        