name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "develop"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: yarn install
      - name: build storybook
        run: yarn build-storybook
      - name: deploy storybook
        uses: YisoTsao/UI-lib@v0.1.0
        with:
          branch: gh-pages
          folder: yarn build-storybook
        